"""Shared helper functions for Verilator rules."""

load("@bazel_tools//tools/cpp:toolchain_utils.bzl", "find_cpp_toolchain")
load("@rules_cc//cc:defs.bzl", "CcInfo")
load("@rules_cc//cc/common:cc_common.bzl", "cc_common")
load("//verilog:defs.bzl", "VerilogInfo")

_SV_SRC = ["sv", "v"]
_CPP_SRC = ["cc", "cpp", "cxx", "c++"]
_HPP_SRC = ["h", "hh", "hpp"]
_RUNFILES = ["dat", "mem"]

def cc_compile_and_link_static_library(
        ctx,
        srcs,
        hdrs,
        deps = [],
        compile_deps = None,
        link_deps = None,
        runfiles = [],
        includes = [],
        defines = []):
    """Compile and link C++ source into a static library.

    Args:
        ctx: Context for rule.
        srcs: The cpp sources generated by verilator.
        hdrs: The headers generated by verilator.
        deps: Library dependencies to build with.
        compile_deps: Library dependencies required while compiling.
        link_deps: Library dependencies required while linking.
        runfiles: Data dependencies that are read at runtime.
        includes: The includes for the verilator module to build.
        defines: Cpp defines to build with.

    Returns:
        Providers containing the compiled library outputs.
    """
    cc_toolchain = find_cpp_toolchain(ctx)
    feature_configuration = cc_common.configure_features(
        ctx = ctx,
        cc_toolchain = cc_toolchain,
        requested_features = ctx.features,
        unsupported_features = ctx.disabled_features,
    )

    compile_deps = deps if compile_deps == None else compile_deps
    link_deps = deps if link_deps == None else link_deps

    compilation_contexts = [dep[CcInfo].compilation_context for dep in compile_deps]
    compilation_context, compilation_outputs = cc_common.compile(
        name = ctx.label.name,
        actions = ctx.actions,
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        user_compile_flags = ctx.attr.copts,
        srcs = srcs,
        includes = includes,
        defines = defines,
        public_hdrs = hdrs,
        compilation_contexts = compilation_contexts,
    )

    linking_contexts = [dep[CcInfo].linking_context for dep in link_deps]
    linking_context, linking_output = cc_common.create_linking_context_from_compilation_outputs(
        actions = ctx.actions,
        feature_configuration = feature_configuration,
        cc_toolchain = cc_toolchain,
        compilation_outputs = compilation_outputs,
        linking_contexts = linking_contexts,
        name = ctx.label.name,
        disallow_dynamic_library = True,
    )

    output_files = []
    if linking_output.library_to_link.static_library != None:
        output_files.append(linking_output.library_to_link.static_library)
    if linking_output.library_to_link.dynamic_library != None:
        output_files.append(linking_output.library_to_link.dynamic_library)

    return [
        DefaultInfo(
            files = depset(output_files),
            runfiles = ctx.runfiles(files = runfiles),
        ),
        CcInfo(
            compilation_context = compilation_context,
            linking_context = linking_context,
        ),
    ]

def only_sv(f):
    """Return the path for SystemVerilog sources, or None otherwise."""
    if f.extension in _SV_SRC:
        return f.path
    return None

def _only_cpp(f):
    if f.extension in _CPP_SRC + _HPP_SRC:
        return f.path
    return None

def _only_hpp(f):
    if f.extension in _HPP_SRC:
        return f.path
    return None

def collect_verilog_inputs(module):
    """Flatten the Verilog DAG into source, include, and runfile lists.

    Args:
        module: A target providing `VerilogInfo`.

    Returns:
        A struct with `includes`, `runfiles`, and flattened `verilog_files`.
    """
    dag_entries = module[VerilogInfo].dag.to_list()
    all_srcs = [entry.srcs for entry in dag_entries]
    all_data = [entry.data for entry in dag_entries]
    all_includes = [include for entry in dag_entries for include in entry.includes]
    all_files = [src for sub_tuple in (all_srcs + all_data) for src in sub_tuple]

    runfiles = []
    verilog_files = []
    for file in all_files:
        if file.extension in _RUNFILES:
            runfiles.append(file)
        else:
            verilog_files.append(file)

    return struct(
        includes = all_includes,
        runfiles = runfiles,
        verilog_files = verilog_files,
    )

def verilator_env(verilator_toolchain):
    """Return the environment shared by all Verilator actions.

    Args:
        verilator_toolchain: The resolved Verilator toolchain info.

    Returns:
        A dictionary of environment variables for Verilator actions.
    """
    env = {}
    if verilator_toolchain._avoid_nondeterministic_outputs:
        env["VERILATOR_AVOID_NONDETERMINISTIC_OUTPUTS"] = "1"
    return env

def copy_generated_cpp_and_hpp(ctx, generated_dir):
    """Split generated tree artifacts into C++ sources and public headers.

    Args:
        ctx: Rule context.
        generated_dir: Tree artifact containing Verilator-generated outputs.

    Returns:
        A struct with `cpp` and `hpp` tree artifacts.
    """
    generated_cpp = ctx.actions.declare_directory(ctx.label.name + "_cpp")
    generated_hpp = ctx.actions.declare_directory(ctx.label.name + "_h")

    cp_args = ctx.actions.args()
    cp_args.add(generated_cpp.path, format = "--src_output=%s")
    cp_args.add(generated_hpp.path, format = "--hdr_output=%s")
    cp_args.add_all([generated_dir], map_each = _only_cpp, format_each = "--src=%s")
    cp_args.add_all([generated_dir], map_each = _only_hpp, format_each = "--hdr=%s")

    ctx.actions.run(
        mnemonic = "VerilatorCopyTree",
        arguments = [cp_args],
        inputs = [generated_dir],
        outputs = [generated_cpp, generated_hpp],
        executable = ctx.executable._copy_tree,
    )

    return struct(
        cpp = generated_cpp,
        hpp = generated_hpp,
    )

def hierarchical_prefix(module_name):
    """Return the Verilator-generated output prefix for a module."""
    return "V" + module_name
